os:
  - linux
  - osx

language: cpp

compiler:
  - gcc
  - clang

env:
  native:
    - CROSS_COMPILE32=0
    - BUNDLED_LIBS=1
    - BUNDLED_SDL=1
    - BUNDLED_JPEG=1
    - BUNDLED_LUA=1
    - BUNDLED_OGG=1

before_script:
  - ./misc/travis-setup.sh

script:
  - ./easybuild.sh

notifications:
  irc:
    template:
      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
    channels:
      - "irc.freenode.org#etlegacy"
    use_notice: true
    skip_join: true
  webhooks:
    urls:
      - https://webhooks.gitter.im/e/5a93d4b59447e6129a58
    on_success: change
    on_failure: always
    on_start: never
