os:
  - linux
  - osx

language: cpp

compiler:
  - gcc
  - clang

env:
  native:
    - CROSS_COMPILE32=0
    - FEATURE_RENDERER2=1
    - RENDERER_DYNAMIC=1
    - BUNDLED_LIBS=1
    - BUNDLED_SDL=1
    - BUNDLED_JPEG=1
    - BUNDLED_LUA=1
    - BUNDLED_OGG=1
    - BUNDLED_CURL=1

before_script:
	- ./misc/travis-setup.sh

script:
  - ./easybuild.sh

notifications:
  irc:
    template:
      - "%{repository}#%{build_number} %{commit} %{author}: %{message} %{build_url}"
    channels:
      - "irc.freenode.org#etlegacy"
    use_notice: true
    skip_join: true
