name: Snapcraft

# Controls when the workflow will run
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["ETLBuild"]
    types:
      - completed

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v4
        with:
          repository: etlegacy/etlegacy-snap
          fetch-depth: 1

      - name: Setup
        uses: canonical/setup-lxd@main
        with:
          group: lxd
        run: |
          sudo apt update && sudo apt install snapd
          sudo snap install snapcraft --classic
      - name: Build SNAP
        run: |
          snapcraft pack
      - name: Publish
        uses: snapcore/action-publish@v1.2.0
        env:
          SNAPCRAFT_STORE_CREDENTIALS: ${{ secrets.SNAPCRAFT_STORE_CREDENTIALS }}
        with:
          snap: ${{ steps.snapcraft.outputs.snap }}
          release: edge
#          release: stable
#          release: candidate
#          release: beta
